name: chatwoot
description: 'Cross-Platform app for chatwoot.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 4.0.0+2

environment:
  sdk: ^3.7.0
  flutter: 3.29.0

dependencies:
  flutter:
    sdk: flutter

  path: any # The path package provides common operations for manipulating paths
  intl: any # Provides internationalization and localization facilities
  flutter_localizations:
    sdk: flutter
  path_provider: any # finding commonly used locations on the filesystem
  universal_io: any # A cross-platform dart:io that works on all platforms, including browsers.
  video_player: any # A Flutter plugin for iOS, Android and Web for playing back video on a Widget surface.

  shared_preferences: ^2.5.2
  dio: ^5.8.0+1 # A powerful HTTP networking package for Dart/Flutter
  dio_http2_adapter: ^2.6.0
  logger: ^2.5.0
  refreshed: ^3.0.0 # This is a refreshed version of GetX
  events_emitter: ^0.6.0
  url_launcher: ^6.3.1 # Launching a URL
  google_fonts: ^6.2.1
  file_picker: ^8.3.5 # native file explorer to pick single or multiple files
  extended_image: ^9.1.0 # A powerful official extension library of images
  flutter_inappwebview: ^6.1.5 # inline webview, to use an headless webview, and to open an in-app browser window
  sqflite: ^2.4.2 # Flutter plugin for SQLite
  flutter_dotenv: # Easily configure any flutter application with global variables using a `.env` file.
    git:
      url: https://github.com/trongtindev/flutter_dotenv.git
  result_dart: ^2.0.0 # Overruns are common in design, and modern architectures always designate a place to handle failures.
  package_info_plus: ^8.2.1 # querying information about an application package
  device_info_plus: ^11.3.0 # Get current device information
  flutter_native_splash: ^2.4.4 # Customize Flutter's default white native splash screen
  flutter_markdown: ^0.7.6+2 # A markdown renderer for Flutter.
  action_cable: ^1.3.0 # ActionCable is the default realtime websocket framework and protocol in Rails.
  flutter_local_notifications: ^18.0.1 # A cross platform plugin for displaying local notifications.
  permission_handler: ^11.3.1 # Request permissions and check their status
  app_settings: ^5.2.0 # for opening iOS and Android phone settings from an app.
  chewie: ^1.10.0 # video player for Flutter with a heart of gold.
  just_audio: ^0.9.46 # feature-rich audio player
  record: ^5.2.0 # Audio recorder from microphone to a given file path or stream.
  flutter_colorpicker: ^1.1.0
  translator: ^1.0.3+1 # Free Google Translate API for Dart

  # desktop
  window_manager: ^0.4.3 # This plugin allows Flutter desktop apps to resizing and repositioning the window.
  sqflite_common_ffi: ^2.3.5 # Linux/Windows/DartVM support

  # tracking
  sentry_flutter: ^8.13.0 # Sentry SDK for Flutter.
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  firebase_analytics: ^11.4.2

  # maybe rewrite
  mime: ^2.0.0 # MIME type definitions and for processing streams of MIME multipart media types.
  timeago: ^3.7.0 # Converts a date into a humanized text

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true # internationalization
  assets:
    - .env.production
    - .env.development
    - .env
    - assets/sqlite/data.sql
    - assets/images/
    - assets/images/icons/
    - assets/images/empty/
    - assets/countryCodes.json

flutter_native_splash:
  color: '#F8F9FF'
  color_dark: '#111418'
  image: assets/images/splash.png
  android_12:
    image: assets/images/adaptive-icon.png
