name: chatwoot
description: 'Mobile app for chatwoot platform. Built with Flutter.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1
  flutter: 3.27.2

dependencies:
  flutter:
    sdk: flutter

  path: ^1.9.0
  path_provider: ^2.1.5
  dio: ^5.7.0
  logger: ^2.5.0
  get: ^4.6.6
  get_storage: ^2.1.1
  events_emitter: ^0.6.0
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  file_picker: ^8.1.7
  cached_network_image: ^3.4.1
  flutter_inappwebview: ^6.1.5 # A Flutter plugin that allows you to add an inline webview
  sqflite: ^2.4.1 # Flutter plugin for SQLite
  flutter_dotenv: # Easily configure any flutter application with global variables using a `.env` file.
    git:
      url: https://github.com/trongtindev/flutter_dotenv.git
  result_dart: ^2.0.0 # Overruns are common in design, and modern architectures always designate a place to handle failures.
  package_info_plus: ^8.1.2
  toastification: ^2.3.0
  timeago: ^3.7.0

  # desktop
  window_manager: ^0.4.3 # This plugin allows Flutter desktop apps to resizing and repositioning the window.
  sqflite_common_ffi: ^2.3.4+4 # Linux/Windows/DartVM support

  # tracking
  sentry_flutter: ^8.12.0 # Sentry SDK for Flutter.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env.production
    - .env.development
    - .env
    - assets/sqlite/data.sql
    - assets/images/
