name: Analyze

on:
  push:
    branches:
      - main
      - beta
      - prod
  pull_request:
    branches:
      - main
      - beta
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true
      - run: flutter --version

      - name: Create .env file
        run: |
          echo "BAR=FOO" >> .env

      - name: Install dependencies
        run: flutter pub get

      - name: Test
        run: flutter test

      - name: analyze
        run: dart analyze
